# OAP to focus a collimated beam, followed by a focal relay with an off-axis ellipsoid

[wavefront]
optic_type = 'poppy.FresnelWavefront'
wavelength = '630nm'
npix = 256
oversample = 4 # inverse of osys.beam_ratio
beam_radius = '0.03m' # 05 * osys.pupil_diameter

[[osys]]
optic_type = 'poppy.FresnelOpticalSystem'
name='OAP OAE Relay'
pupil_diameter='0.06m' # 2x wavefront.beam_radius
npix=256
beam_ratio = 0.25 # inverse of wavefront.oversample

[[osys.optics]]
name = 'EP'
optic_type = 'poppy.CircularAperture'
radius = '0.03m'

[[osys.optics]]
name='OAP1'
is_compound = true
dz='0.99437500000m'
[[osys.optics.optics]]
name='stop'
optic_type = 'poppy.CircularAperture'
radius = '0.1m'
[[osys.optics.optics]]
name = 'surface'
optic_type = 'poppy_utils.ABCPSDWFE'
amp_params = [1, 3, 2.5] # abc PSD
wfe_params = [1, 3, 2.5] # abc PSD
wfe_rms = 20.0
amp_rms = 0.005
#[[osys.optics.optics]]
#optic_type = 'None'
#jones_matrix = 'None'

[[osys.optics]] # Fresnel optical systems don't behave if powered optics are members of CompoundAnalyticOptics
name = 'OAP1_power'
optic_type = 'poppy_utils.ConicPhase'
roc = '2.0m'
oad = '0.150m'
k = -1

[[osys.optics]]
name = 'IFP'
optic_type = 'poppy.ScalarTransmission'
dz='1.0056250000m'

[[osys.optics]]
name = 'OAE'
is_compound = true
dz='1.3867600234m'
[[osys.optics.optics]]
name = 'stop'
optic_type = 'poppy.CircularAperture'
radius = '0.1m'
[[osys.optics.optics]]
name = 'surface'
optic_type = 'poppy_utils.ABCPSDWFE'
amp_params = [1, 3, 2.5] # abc PSD
wfe_params = [1, 3, 2.5] # abc PSD
wfe_rms = 20.0
amp_rms = 0.005
#[[osys.optics.optics]]
#optic_type = 'None'
#jones_matrix = 'None'

[[osys.optics]]
name = 'OAE_power'
optic_type = 'poppy_utils.ConicPhase'
roc = '2.0m'
oad = '0.207m'
k = -0.2

[[osys.optics]]
name = 'XP'
optic_type = 'poppy.ScalarTransmission'
dz='1.0132638996m'

[[osys.optics]]
name = 'Detector'
dz = '2.5999761429m'
optic_type = 'poppy.Detector'
pixelscale = '10micron/pixel'
fov_pixels = 75
