[metadata]
notes = 'First attempt at implementing SVC with Poppy.'

# ---- Pre-FPM optical system ----

[wavefront]
optic_type = 'poppy.PolarizedFresnelWavefront'
wavelength = '475nm'
npix = 1024
oversample = 4 # inverse of osys.beam_ratio
beam_radius = '0.03m' # 05 * osys.pupil_diameter

[[osys]]
optic_type = 'poppy.FresnelOpticalSystem'
name='Pre-FPM'
pupil_diameter='0.06m' # 2x wavefront.beam_radius
npix=1024
beam_ratio = 0.25 # inverse of wavefront.oversample

[[osys.optics]]
name = 'EP'
optic_type = 'poppy.CircularAperture'
radius = '0.03m'

[[osys.optics]]
name='OAP1'
is_compound= 'True'
dz='0.99437500000m'
[[osys.optics.optics]]
name = 'OAP1_stop'
optic_type = 'poppy.CircularAperture'
radius = '0.1m'
# [[osys.optics.optics]]
# name = 'surface'
# optic_type = 'poppy_utils.ABCPSDWFE'
# amp_params = [1, 3, 2.5] # abc PSD
# wfe_params = [1, 3, 2.5] # abc PSD
# wfe_rms = 5.0 # CHECK! MAY NEED UNITS HERE
# amp_rms = 0.005

[[osys.optics]]
name='SVC'
optic_type='poppy_utils.ScalarVortexMask'
f_number = 51.2
dimple_radius=0.621
svc_type = 'sawtooth'
is_compound='True'
[[osys.optics.optics]]
name='SVC_stop'
optic_type = 'poppy.CircularAperture'
radius='10mm'

[[osys.optics]]
name = 'Science detector'
dz = '246.35742217700002mm' # distance from OAP7 to detector
optic_type = 'poppy.Detector'
pixelscale = '3.76micron/pixel' #3.76micron/pixel'
fov_pixels = 500